name: snake CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu_20:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc python3 python3-pip && pip3 install setuptools cython numpy
    - name: slow5lib
      run: git clone https://github.com/hasindu2008/slow5lib && cd slow5lib && python3 setup.py install --user && cd ..
    - name: install
      run:  python3 setup.py install --user && blue-crab --help
    - name: test
      run: test/test.sh
  ubuntu_22:
    name: ubuntu-22.04
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc python3 python3-pip && pip3 install setuptools cython numpy
    - name: slow5lib
      run: git clone https://github.com/hasindu2008/slow5lib && cd slow5lib && python3 setup.py install --user && cd ..
    - name: install
      run:  python3 setup.py install --user && blue-crab --help
    - name: test
      run: test/test.sh
  ubuntu_24:
    name: ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc python3 python3-pip && pip3 install --break-system-packages setuptools cython numpy
    - name: slow5lib
      run: git clone https://github.com/hasindu2008/slow5lib && cd slow5lib && python3 setup.py install --user && cd ..
    - name: install
      run:  python3 setup.py install --user && blue-crab --help
    - name: test
      run: test/test.sh
  arm64:
    name: pyslow5 ubuntu arm
    runs-on: ubuntu-latest
    steps:
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - uses: docker://multiarch/ubuntu-core:arm64-focal
      with:
        args: 'uname -a'
    - uses: actions/checkout@v1
    - uses: docker://multiarch/ubuntu-core:arm64-focal
      with:
        args: >
          bash -c "apt-get update &&
          apt-get install -y zlib1g-dev gcc make python3 python3-pip git wget &&
          pip3 install setuptools cython numpy &&
          ldd --version && gcc --version && python3 --version &&
          git clone https://github.com/hasindu2008/slow5lib && cd slow5lib && pip3 install . && cd .. &&
          pip3 install --upgrade pip && rm /usr/lib/python3/dist-packages/pip && pip3 --version && pip3 install .  && blue-crab --help && test/test.sh"
  os_x_12:
    name: macos-12
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: pip3 install numpy
    - name: slow5lib
      run: git clone https://github.com/hasindu2008/slow5lib && cd slow5lib  && pip3 install . && cd ..
    - name: install
      run:  pip3 install . && blue-crab --help
    - name: test
      run: test/test.sh
  os_x_13:
    name: macos-13
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: pip3 install numpy
    - name: slow5lib
      run: git clone https://github.com/hasindu2008/slow5lib && cd slow5lib  && pip3 install . && cd ..
    - name: install
      run:  pip3 install . && blue-crab --help
    - name: test
      run: test/test.sh
  os_x_14:
    name: macos-14
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: pip3 install --break-system-packages numpy
    - name: slow5lib
      run: git clone https://github.com/hasindu2008/slow5lib && cd slow5lib  && pip3 install --break-system-packages . && cd ..
    - name: install
      run:  pip3 install --break-system-packages . && blue-crab --help
    - name: test
      run: test/test.sh
